class Trinket {
  constructor(description) {
    this.description = description;
    this.type = "Trinket";
  }
}

export const trinkets = [
  new Trinket("A mummified goblin hand"),
  new Trinket("A piece of crystal that faintly glows in the moonlight"),
  new Trinket("A gold coin minted in an unknown land"),
  new Trinket("A diary written in a language you don’t know"),
  new Trinket("A brass ring that never tarnishes"),
  new Trinket("An old chess piece made from glass"),
  new Trinket("A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips"),
  new Trinket("A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it"),
  new Trinket("A rope necklace from which dangles four mummified elf fingers"),
  new Trinket("The deed for a parcel of land in a realm unknown to you"),
  new Trinket("A 1-ounce block made from an unknown material"),
  new Trinket("A small cloth doll skewered with needles"),
  new Trinket("A tooth from an unknown beast"),
  new Trinket("An enormous scale, perhaps from a dragon"),
  new Trinket("A bright green feather"),
  new Trinket("An old divination card bearing your likeness"),
  new Trinket("A glass orb filled with moving smoke"),
  new Trinket("A 1-pound egg with a bright red shell"),
  new Trinket("A pipe that blows bubbles"),
  new Trinket("A glass jar containing a weird bit of flesh floating in pickling fluid"),
  new Trinket("A tiny gnome-crafted music box that plays a song you dimly remember from your childhood"),
  new Trinket("A small wooden statuette of a smug halfling"),
  new Trinket("A brass orb etched with strange runes"),
  new Trinket("A multicolored stone disk"),
  new Trinket("A tiny silver icon of a raven"),
  new Trinket("A bag containing forty-seven humanoid teeth, one of which is rotten"),
  new Trinket("A shard of obsidian that always feels warm to the touch"),
  new Trinket("A dragon's bony talon hanging from a plain leather necklace"),
  new Trinket("A pair of old socks"),
  new Trinket("A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking"),
  new Trinket("A silver badge in the shape of a five-pointed star"),
  new Trinket("A knife that belonged to a relative"),
  new Trinket("A glass vial filled with nail clippings"),
  new Trinket("A rectangular metal device with two tiny metal cups on one end that throws sparks when wet"),
  new Trinket("A white, sequined glove sized for a human"),
  new Trinket("A vest with one hundred tiny pockets"),
  new Trinket("A small, weightless stone block"),
  new Trinket("A tiny sketch portrait of a goblin"),
  new Trinket("An empty glass vial that smells of perfume when opened"),
  new Trinket("A gemstone that looks like a lump of coal when examined by anyone but you"),
  new Trinket("A scrap of cloth from an old banner"),
  new Trinket("A rank insignia from a lost legionnaire"),
  new Trinket("A tiny silver bell without a clapper"),
  new Trinket("A mechanical canary inside a gnome-crafted lamp"),
  new Trinket("A tiny chest carved to look like it has numerous feet on the bottom"),
  new Trinket("A dead sprite inside a clear glass bottle"),
  new Trinket("A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)"),
  new Trinket("A glass orb filled with water, in which swims a clockwork goldfish"),
  new Trinket("A silver spoon with an M engraved on the handle"),
  new Trinket("A whistle made from gold-colored wood"),
  new Trinket("A dead scarab beetle the size of your hand"),
  new Trinket("Two toy soldiers, one with a missing head"),
  new Trinket("A small box filled with different-sized buttons"),
  new Trinket("A candle that can’t be lit"),
  new Trinket("A tiny cage with no door"),
  new Trinket("An old key"),
  new Trinket("An indecipherable treasure map"),
  new Trinket("A hilt from a broken sword"),
  new Trinket("A rabbit’s foot"),
  new Trinket("A glass eye"),
  new Trinket("A cameo carved in the likeness of a hideous person"),
  new Trinket("A silver skull the size of a coin"),
  new Trinket("An alabaster mask"),
  new Trinket("A pyramid of sticky black incense that smells very bad"),
  new Trinket("A nightcap that, when worn, gives you pleasant dreams"),
  new Trinket("A single caltrop made from bone"),
  new Trinket("A gold monocle frame without the lens"),
  new Trinket("A 1-inch cube, each side painted a different color"),
  new Trinket("A crystal knob from a door"),
  new Trinket("A small packet filled with pink dust"),
  new Trinket("A fragment of a beautiful song), written as musical notes on two pieces of parchment"),
  new Trinket("A silver teardrop earring made from a real teardrop"),
  new Trinket("The shell of an egg painted with scenes of human misery in disturbing detail"),
  new Trinket("A fan that, when unfolded, shows a sleeping cat"),
  new Trinket("A set of bone pipes"),
  new Trinket("A four-leaf clover pressed inside a book discussing manners and etiquette"),
  new Trinket("A sheet of parchment upon which is drawn a complex mechanical contraption"),
  new Trinket("An ornate scabbard that fits no blade you have found so far"),
  new Trinket("An invitation to a party where a murder happened"),
  new Trinket("A bronze pentacle with an etching of a rat's head in its center"),
  new Trinket("A purple handkerchief embroidered with the name of a powerful archmage"),
  new Trinket("Half of a floorplan for a temple, castle, or some other structure"),
  new Trinket("A bit of folded cloth that, when unfolded, turns into a stylish cap"),
  new Trinket("A receipt of deposit at a bank in a far-flung city"),
  new Trinket("A diary with seven missing pages"),
  new Trinket("An empty silver snuffbox bearing an inscription on the surface that says “dreams”"),
  new Trinket("An iron holy symbol devoted to an unknown god"),
  new Trinket("A book that tells the story of a legendary hero's rise and fall, with the last chapter missing"),
  new Trinket("A vial of dragon blood"),
  new Trinket("An ancient arrow of elven design"),
  new Trinket("A needle that never bends"),
  new Trinket("An ornate brooch of dwarven design"),
  new Trinket("An empty wine bottle bearing a pretty label that says), “The Wizard of Wines Winery), Red Dragon Crush), 331422-W”"),
  new Trinket("A mosaic tile with a multicolored, glazed surface"),
  new Trinket("A petrified mouse"),
  new Trinket("A black pirate flag adorned with a dragon's skull and crossbones"),
  new Trinket("A tiny mechanical crab or spider that moves about when it’s not being observed"),
  new Trinket("A glass jar containing lard with a label that reads, Griffon Grease"),
  new Trinket("A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body"),
  new Trinket("A metal urn containing the ashes of a hero"),
];
